const HP_SUPA='https://iapnejlttsqqefkpmelp.supabase.co';const HP_KEY='sb_publishable_TB7oC4nDlUJq-Gcb2yoTjQ_Dvbh6NlM';
async function hpRpc(fn,args){try{const r=await fetch(HP_SUPA+'/rest/v1/rpc/'+fn,{method:'POST',headers:{apikey:HP_KEY,'Content-Type':'application/json'},body:JSON.stringify(args||{})});const text=await r.text();let data;try{data=JSON.parse(text)}catch{data={ok:false,error:text||('Request failed with HTTP '+r.status)}}if(!r.ok)return {ok:false,error:data.message||data.error||('Request failed with HTTP '+r.status),details:data};return data}catch(e){return {ok:false,error:'Could not reach the account server. Check your connection and try again.'}}}
function hpToken(){return localStorage.getItem('hyperpop_token')}
async function hpMigrateSession(){const t=localStorage.getItem('hyperpop_token');if(!t||sessionStorage.getItem('hyperpop_migration_done'))return;try{const r=await fetch(HP_SUPA+'/functions/v1/hyperpop-migrate-session',{method:'POST',headers:{'Content-Type':'application/json','x-hyperpop-session':t}});const d=await r.json().catch(()=>({}));if(r.ok&&d.ok&&d.token){localStorage.setItem('hyperpop_token',d.token);sessionStorage.setItem('hyperpop_migration_done','1');if(d.avatar_migrated)sessionStorage.setItem('hyperpop_avatar_migrated','1')}}catch(e){}}
async function hpMe(){const t=hpToken();if(!t)return null;const x=await hpRpc('hyperpop_me',{p_token:t});return x?.ok?x:null}
async function hpSubmit(game,score){const t=hpToken();if(!t){alert('Log in to submit your score to the leaderboard!');return false}const x=await hpRpc('hyperpop_submit_score',{p_token:t,p_game:game,p_score:score});if(!x.ok)alert(x.error||'Could not submit score.');return !!x.ok}
async function hpSetAvatar(dataUrl){const t=hpToken();if(!t)return {ok:false,error:'Not signed in.'};try{const src=await fetch(dataUrl);if(!src.ok)throw new Error('Could not read the selected image.');const blob=await src.blob();let file=blob;if(!['image/png','image/jpeg','image/webp','image/gif'].includes(blob.type)){const img=new Image();img.src=dataUrl;await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=()=>reject(new Error('That image format is not supported.'))});const canvas=document.createElement('canvas');const max=512;const scale=Math.min(1,max/Math.max(img.naturalWidth||img.width,img.naturalHeight||img.height));canvas.width=Math.max(1,Math.round((img.naturalWidth||img.width)*scale));canvas.height=Math.max(1,Math.round((img.naturalHeight||img.height)*scale));const out=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.88));if(!out)throw new Error('Could not convert the image.');file=out}const ext=file.type==='image/png'?'png':file.type==='image/webp'?'webp':file.type==='image/gif'?'gif':'jpg';const path='avatars/'+crypto.randomUUID()+'.'+ext;const up=await fetch(HP_SUPA+'/storage/v1/object/hyperpop-avatars/'+path,{method:'POST',headers:{apikey:HP_KEY,'Content-Type':file.type||'image/jpeg'},body:file});if(!up.ok){const msg=await up.text().catch(()=> '');return {ok:false,error:'Cloud upload failed ('+up.status+'). '+(msg||'Storage rejected the image.')};}const url=HP_SUPA+'/storage/v1/object/public/hyperpop-avatars/'+path;return await hpRpc('hyperpop_set_avatar',{p_token:t,p_avatar_url:url})}catch(e){return {ok:false,error:e?.message||'Could not upload that picture.'}}}
async function hpLogout(){const t=hpToken();if(t)await hpRpc('hyperpop_logout',{p_token:t});localStorage.removeItem('hyperpop_token');location.reload()}
async function hpAccountBar(){const slot=document.getElementById('account-slot');const nav=document.querySelector('nav');const target=slot||nav;if(!target)return;const bar=document.createElement('div');bar.className='accountbar';const me=await hpMe();if(me){bar.innerHTML='<a class="profile-pill" href="accounts.html">'+(me.avatar_url?'<img class="profile-img" src="'+me.avatar_url+'" alt="">':'<span class="profile-dot">'+me.username.slice(0,1).toUpperCase()+'</span>')+'<span>@'+me.username+'</span></a>'}else{bar.innerHTML='<a class="profile-pill" href="accounts.html">👤 Login / Sign up</a>'}target.appendChild(bar)}document.addEventListener('DOMContentLoaded',async()=>{await hpMigrateSession();hpAccountBar()});
